### ISSUE TITLE
Unable To Find sku_value

### ISSUE THREAD

**Issue by saderra** [elastic/app-search-magento#65] opened 2019-10-14 18:07 UTC
Received the following errors this morning on my staging 2.3.2 environment and my development 2.3.3 environment: Exception #0 (Magento\Framework\Exception\LocalizedException): Unable to find field sku_value.

Staging: This event happened when trying to search or navigate into the Magento catalog. 
https://c9.saderra.com/catalog/category/view/s/boat-covers/id/12/

Development: Same condition to reproduce:
https://classic.saderra.com/patio/shop-by-collection/storigami

**Comment by afoucret** [comment] 2019-10-15 06:55
Hi, I will need much more context on what are you trying to achieve.

From my understanding, your are trying to build a facet on the SKU but this attribute can not be set as filterable by default in Magento. 

Are you using a different SKU attribute (sku_value) or the standard SKU attribute to do it? If using another attribute, how is this attribute configured (is filterable ? Backend model model ? Source model?)

**Comment by saderra** [comment] 2019-10-15 06:58
I’m not trying to do anything like that. After running the update you made last night, this is the new error that shows up on every page. Just go the website, and click on any category link - the error comes up. 


You can see for yourself here: 

Magento Access: 

Website: https://classic.saderra.com <https://classic.saderra.com/>
Magento Backend: https://classic.saderra.com/newportcenter <https://classic.saderra.com/newportcenter>
Magento User: elastic
Magento Pass: FFuRet6&c46X9

Server SSH: 

ssh: 138.68.6.167
user: mexbs
pass: dd&gh$r#t23DrF
location: /var/www/html

**Comment by romain-chanu** [comment] 2019-10-15 07:00
@saderra - please do not provide any credentials. This is a public repository. @afoucret and I will follow-up with you regarding your issue.

**Comment by saderra** [comment] 2019-10-15 07:05
@afoucret @afoucret you are MORE than welcome to login to the credentials I sent and make adjustments as needed to the extension. That's a dev server that I'm only keeping up and running for the purposes of ensuring this extension works. Once we verify the extension works I'm shutting that down.

**Comment by afoucret** [comment] 2019-10-15 12:20
Hi @saderra, I have double-checked and the bug is caused by a third party extension.

The Amasty Part Finder module ha a logic to create facet on a field called `sku_value` that does not exist in Magento standard search engine. You can find the declaration in the `vendor/amasty/finder/etc/search_request.xml` file:

```xml
<bucket name="sku_value_bucket" field="sku_value" xsi:type="termBucket">
   <metrics>
       <metric type="count"/>
    </metrics>
</bucket>
```

Because this field does not exist in the Magento standard search engine they had to implement their own logic to add it into the ElasticSearch indexing (code located inside `vendor/amasty/finder/Plugin/Elasticsearch`). Unfortunately, the same work needs to be done with AppSearch in order to get things working as expected.

From what I have seen this field is a pure copy of the SKU field (added for technical reasons that are related to ElasticSearch). The most straightforward method to deal with this issue is probably to try to use a new field name resolver in App Search.

To be complete on this issue, I don't consider it as an issue of the App Search module but more as an issue related to the third party module.

It is likely that you will meet additional issues with this module because it changes heavily the behavior of Magento search engine (to build something which is not related to search). Moreover, it is designed without considering other search engines than those shipped with Magento out-of-the-box. Sadly, there is nothing we can do about this and this is something I often have to deal with in the past with modules from Amasty.

**Comment by afoucret** [comment] 2019-10-15 13:01
To override the field used by Amasty in the search request:

1. Create a new module (Saderra_AppSearchPartFinder in my example)

2. Create the `Saderra\AppSearchPartFinder\etc\search_request.xml` file with the following content:

```xml
<?xml version="1.0"?>

<requests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="urn:magento:framework:Search/etc/search_request.xsd">
    <request query="catalog_view_container">
        <aggregations>
            <bucket name="sku_value_bucket" field="sku" xsi:type="termBucket">
                <metrics>
                    <metric type="count"/>
                </metrics>
            </bucket>
        </aggregations>
    </request>

    <request query="quick_search_container">
        <aggregations>
            <bucket name="sku_value_bucket" field="sku" xsi:type="termBucket">
                <metrics>
                    <metric type="count"/>
                </metrics>
            </bucket>
        </aggregations>
    </request>
</requests>
```

3. Make sure your module is loaded after Elastic AppSearch and Amasty Parts finder:

```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="ElasticAppSearch_CatalogSearch" setup_version="0.0.1">
        <sequence>
            <module name="ElasticAppSearch_CatalogSearch" />
            <module name="Amasty_Finder" />
        </sequence>
    </module>
</config>
```

4. Clean cache and refresh

**Comment by afoucret** [comment] 2019-10-15 13:03
I close the issue because it is clearly not a bug of the module but a problem caused by a third party module.

I would be happy to continue the discussion on the proposed workaround.

**Closed by afoucret** 2019-10-15 13:03 UTC

**Comment by saderra** [comment] 2019-10-15 15:14
I get the following error when attempting to enable the module: 

There are no commands defined in the "module" namespace.

**Comment by saderra** [comment] 2019-10-15 15:43
Where does this code go?

**Comment by afoucret** [comment] 2019-10-16 15:48
Here is a step by step guide of how to create the module (inspired by this [official Magento doc](https://devdocs.magento.com/videos/fundamentals/create-a-new-module/)).

1. Create the module directory in `app/code`:

```
mkdir app/code/Saderra/AppSearchPartFinder/etc
```

2. Create the `app/code/Saderra/AppSearchPartFinder/etc/module.xml` file:

```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Saderra_AppSearchPartFinder" setup_version="0.0.1">
        <sequence>
            <module name="ElasticAppSearch_CatalogSearch" />
            <module name="Amasty_Finder" />
        </sequence>
    </module>
</config>
```

**Note:** We want to make sure the module is loaded after both `ElasticAppSearch_CatalogSearch` and `Amasty_Finder` modules in order to rewrite their XML files.

3. Create the module registration file `app/code/Saderra/AppSearchPartFinder/registration.php`:

```php
<?php 
\Magento\Framework\Component\ComponentRegistrar::register(
  \Magento\Framework\Component\ComponentRegistrar::MODULE, 
  'Saderra_AppSearchPartFinder',
  __DIR__
);
```

4. Add the search request customization file `app/code/Saderra/AppSearchPartFinder/etc/search_request.xml`:

```xml
<?xml version="1.0"?>

<requests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="urn:magento:framework:Search/etc/search_request.xsd">
    <request query="catalog_view_container">
        <aggregations>
            <bucket name="sku_value_bucket" field="sku" xsi:type="termBucket">
                <metrics>
                    <metric type="count"/>
                </metrics>
            </bucket>
        </aggregations>
    </request>

    <request query="quick_search_container">
        <aggregations>
            <bucket name="sku_value_bucket" field="sku" xsi:type="termBucket">
                <metrics>
                    <metric type="count"/>
                </metrics>
            </bucket>
        </aggregations>
    </request>
</requests>
```

5. Setup the module:

```
bin/magento cache:clean
bin/magento setup:upgrade
```

**Comment by saderra** [comment] 2019-10-16 17:04
Please see errors output by this recommendation: 

https://c1.saderra.com/rv <https://c1.saderra.com/rv>

**Comment by saderra** [comment] 2019-10-16 17:16
This does load after the other modules: 

        'Amasty_BannersLite' => 1,
        'Amasty_Base' => 1,
        'Amasty_Geoip' => 1,
        'Amasty_Conditions' => 1,
        'Amasty_Coupons' => 1,
        'Amasty_CronScheduleList' => 1,
        'Amasty_Customform' => 0,
        'Amasty_Finder' => 1,
        'Amasty_Followup' => 1,
        'Amasty_Checkout' => 0,
        'Amasty_InvisibleCaptcha' => 0,
        'Amasty_ProductAttachment' => 1,
        'Amasty_Promo' => 1,
        'Amasty_PromoBanners' => 1,
        'Amasty_Rgrid' => 1,
        'Amasty_SalesRuleWizard' => 1,
        'Amasty_SeoRichData' => 1,
        'Amasty_Smtp' => 1,
        'Amasty_XmlSitemap' => 1,
        'Amazon_Core' => 0,
        'Amazon_Login' => 0,
        'Amazon_Payment' => 0,
        'Bazaarvoice_Connector' => 1,
        'Cart2Quote_Quotation' => 1,
        'Cart2Quote_Features' => 1,
        'Cart2Quote_FormReqDisabler' => 1,
        'Cart2Quote_License' => 1,
        'Cart2Quote_AutoProposal' => 1,
        'ClassicAccessories_IO' => 1,
        'ClassyLlama_AvaTax' => 1,
        'Dotdigitalgroup_Email' => 0,
        'ElasticAppSearch_Search' => 1,
        'ElasticAppSearch_Synonyms' => 1,
        'ElasticAppSearch_CatalogSearch' => 1,
        'ElasticAppSearch_CatalogGraphQl' => 1,
        'Firebear_ImportExport' => 1,
        'Iazel_RegenProductUrl' => 1,
        'Klarna_Core' => 0,
        'Klarna_Ordermanagement' => 0,
        'Klarna_Kp' => 0,
        'Magento_PaypalReCaptcha' => 1,
        'MSP_TwoFactorAuth' => 1,
        'MagePal_CheckoutSuccessMiscScript' => 1,
        'MagePal_Reindex' => 1,
        'Magefan_WysiwygAdvanced' => 0,
        'Mageplaza_Core' => 1,
        'Mageplaza_GoogleRecaptcha' => 1,
        'Mageplaza_Security' => 0,
        'Mageplaza_TwoFactorAuth' => 0,
        'Mexbs_Tieredcoupon' => 1,
        'Mirasvit_Core' => 1,
        'Mirasvit_Feed' => 1,
        'Mirasvit_Kb' => 1,
        'Mirasvit_Misspell' => 0,
        'Mirasvit_Report' => 1,
        'Mirasvit_Search' => 0,
        'Mirasvit_SearchAutocomplete' => 0,
        'Mirasvit_SearchElastic' => 0,
        'Mirasvit_SearchElasticNative' => 0,
        'Mirasvit_SearchLanding' => 0,
        'Mirasvit_SearchMysql' => 0,
        'Mirasvit_SearchReport' => 0,
        'Mirasvit_Sorting' => 0,
        'Saderra_AppSearchPartFinder' => 1,
        'Scriptlodge_UrlRewrite' => 1,
        'Solwin_Bannerslider' => 1,
        'Solwin_Base' => 1,
        'Solwin_CatalogPages' => 1,
        'Solwin_Core' => 1,
        'Solwin_Instagram' => 1,
        'Temando_Shipping' => 0,
        'Vertex_Tax' => 0,
        'WeltPixel_Backend' => 1,
        'WeltPixel_MobileDetect' => 1,
        'WeltPixel_Newsletter' => 1

**Comment by afoucret** [comment] 2019-10-17 04:48
I have updated the content of the `search_request.xml` file in my previous comment. You should try updating it and clean the cache again.

**Comment by saderra** [comment] 2019-10-17 05:09
Excellent. Appears to be working. Do you know when the rest of the functions will also be working? https://swiftype.com/solutions/magento-search <https://swiftype.com/solutions/magento-search>
